### ISSUE TITLE
Exception caught by widgets library: Looking up a deactivated widget's ancestor is unsafe.

### ISSUE THREAD

**Issue by flypigz** [gzlock/flutter_stacked_listview#2]
The following assertion was thrown while finalizing the widget tree:
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

**Comment by gzlock** [comment]
v1.0.4 Fixed this issue and had a breaking change.
* onRemove(int index) changed to onRemove(int index, AxisDirection dir)
* beforeRemove(int index) changed to beforeRemove(int index, AxisDirection dir)

And upload a example video https://www.youtube.com/watch?v=B-U6BHam16I
